#!/usr/bin/env python3
"""Generate the wolf test fixture packages.

The tests in src/tests/auto read a directory of small packages that the build passes as the
WOLF_TEST_FIXTURES_SOURCE environment variable. Those packages used to be tracked in the repository;
they are generated now, so the repository carries test code rather than package artifacts.

The table below is the single source of the fixture content. It was recorded from the object store
rather than from a working tree, because a Windows checkout rewrites most of those files to CRLF,
and the script writes UTF-8 with line feeds so that the generated bytes match the recorded ones.

Usage:
    python3 scripts/make-test-fixtures.py --output build/test-fixtures
    python3 scripts/make-test-fixtures.py --check build/test-fixtures
    python3 scripts/make-test-fixtures.py --list
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Recorded from the fixture packages that were tracked before commit 2925536.
PACKAGES = {
    # The package this repository ships, rather than a test fixture: the release script
    # archives it and the port pins the hash of that archive. Generated from this table so
    # that the repository carries declarations instead of package artifacts.
    'wolf-lang-zxx': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/lang-zxx",\n    "version": "1.0.0.0",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "vendor": "wolf",\n    "copyright": "Copyright (C) wolf",\n    "description": "Passthrough language for text that carries no linguistic content.",\n    "contributions": {\n        "linguist": [\n            { "id": "zxx-passthrough", "path": "./linguists/zxx-passthrough/linguist.json" }\n        ],\n        "inference": [\n            { "id": "zxx-g2p", "path": "./inferences/zxx-g2p/inference.json" },\n            { "id": "zxx-s2p", "path": "./inferences/zxx-s2p/inference.json" }\n        ]\n    }\n}\n',
        'inferences/zxx-g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Passthrough G2P",\n    "exports": {\n        "languages": [\n            { "language": "zxx", "scheme": "passthrough" }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "regex", "value": ["(\\\\p{N})", "(\\\\p{P})", "([.]+)"], "mode": "copy" }\n                    ]\n                }\n            },\n            {\n                "step": "fallback",\n                "params": { "useOriginal": true }\n            }\n        ]\n    }\n}\n',
        'inferences/zxx-s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "Passthrough S2P",\n    "exports": {\n        "languages": [\n            { "language": "zxx", "scheme": "passthrough" }\n        ]\n    },\n    "configuration": {}\n}\n',
        'linguists/zxx-passthrough/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": {\n        "_": "Passthrough",\n        "zh-CN": "直通"\n    },\n    "language": "zxx",\n    "scheme": "passthrough",\n    "exports": {\n        "phonemes": [],\n        "openSet": true\n    },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/zxx-g2p" },\n        { "role": "linguist/s2p", "ref": ":inference/zxx-s2p" }\n    ]\n}\n',
    },

    'bad-language': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-bad-language",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn1-pinyin", "path": "./linguists/x/linguist.json" } ]\n    }\n}\n',
        'linguists/x/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn1", "scheme": "pinyin" }\n',
    },
    'bad-scheme': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-bad-scheme",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ]\n    }\n}\n',
        'linguists/x/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn", "scheme": "-pinyin" }\n',
    },
    'compat-consumer': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-compat-consumer",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "Stands in for a voicebank published against packaging revision 2 and never rebuilt.",\n    "dependencies": [\n        { "id": "wolf/test-compat-provider", "version": "1.0.0.2" }\n    ]\n}\n',
    },
    'compat-consumer-too-new': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-compat-consumer-too-new",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "Asks for a revision newer than anything installed, so it must not resolve. Without this the positive case would pass even if the loader ignored the requested version entirely.",\n    "dependencies": [\n        { "id": "wolf/test-compat-provider", "version": "1.0.0.4" }\n    ]\n}\n',
    },
    'compat-provider': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-compat-provider",\n    "version": "1.0.0.3",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "Stands in for a language package at packaging revision 3, whose compatibility floor is revision 0. It carries no contributions: the subject is version resolution, nothing else."\n}\n',
    },
    'exports-unknown-key': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-exports-unknown-key",\n    "version": "1.0.0.0",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "A language whose composition stops at the pronunciation layer: it declares no linguist/s2p role, which is the shape a language package has when a voicebank supplies the phoneme stage.",\n    "contributions": {\n        "linguist": [\n            {\n                "id": "nld-ds",\n                "path": "./linguists/x/linguist.json"\n            }\n        ],\n        "inference": [\n            {\n                "id": "g2p",\n                "path": "./inferences/g2p/inference.json"\n            }\n        ]\n    }\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Fixed output G2P",\n    "exports": {\n        "languages": [ { "language": "nld", "scheme": "ds" } ],\n        "symbols": [ "a", "b" ],\n        "openSet": false\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            { "step": "fallback", "params": { "useOriginal": false, "defaultPronunciation": "a b" } }\n        ]\n    }\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Pronunciation only",\n    "language": "nld",\n    "scheme": "ds",\n    "exports": {\n        "phonemes": [\n            "a",\n            "b",\n            "c",\n            "d"\n        ],\n        "openSet": false,\n        "phoneme": [\n            "a"\n        ]\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/g2p"\n        }\n    ]\n}\n',
    },
    'lang-chain': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-chain",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [\n            {\n                "id": "eng",\n                "path": "./linguists/eng/linguist.json"\n            },\n            {\n                "id": "deu",\n                "path": "./linguists/deu/linguist.json"\n            }\n        ],\n        "inference": [\n            {\n                "id": "g2p",\n                "path": "./inferences/g2p/inference.json"\n            },\n            {\n                "id": "s2p",\n                "path": "./inferences/s2p/inference.json"\n            },\n            {\n                "id": "nofallback",\n                "path": "./inferences/nofallback/inference.json"\n            },\n            {\n                "id": "s2p-deu",\n                "path": "./inferences/s2p-deu/inference.json"\n            }\n        ]\n    }\n}\n',
        'inferences/g2p/dict.txt': 'hello\thh ax l ow\nhello(2)\thh eh l ow\nread\tr iy d\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Chain G2P",\n    "exports": {\n        "languages": [ { "language": "eng", "scheme": "arpabet" } ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "regex", "value": ["([A-Za-z]+)"], "mode": "convert" },\n                        { "type": "array", "value": ["-"], "mode": "copy" }\n                    ]\n                }\n            },\n            { "step": "dict",   "params": { "file": "./dict.txt" } },\n            { "step": "format", "params": { "operations": ["lowercase"] } },\n            { "step": "dict",   "params": { "file": "./dict.txt" } },\n            { "step": "dict",   "params": { "file": "./dict.txt" }, "enabled": false },\n            { "step": "fallback", "params": { "useOriginal": false, "defaultPronunciation": "" } }\n        ]\n    }\n}\n',
        'inferences/nofallback/dict.txt': 'hello\thh ax l ow\nhello(2)\thh eh l ow\nread\tr iy d\n',
        'inferences/nofallback/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Chain G2P without a fallback",\n    "exports": {\n        "languages": [ { "language": "deu", "scheme": "ds" } ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "regex", "value": ["([A-Za-z]+)"], "mode": "convert" },\n                        { "type": "array", "value": ["-"], "mode": "copy" }\n                    ]\n                }\n            },\n            { "step": "dict",   "params": { "file": "./dict.txt" } },\n            { "step": "format", "params": { "operations": ["lowercase"] } },\n            { "step": "dict",   "params": { "file": "./dict.txt" } },\n            { "step": "dict",   "params": { "file": "./dict.txt" }, "enabled": false }\n        ]\n    }\n}\n',
        'inferences/s2p-deu/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "German S2P",\n    "exports": {\n        "languages": [\n            {\n                "language": "deu",\n                "scheme": "ds"\n            }\n        ]\n    },\n    "configuration": {}\n}\n',
        'inferences/s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "Chain S2P",\n    "exports": {\n        "languages": [ { "language": "eng", "scheme": "arpabet" } ]\n    },\n    "configuration": {}\n}\n',
        'linguists/deu/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Chain German",\n    "language": "deu",\n    "scheme": "ds",\n    "exports": {\n        "phonemes": []\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/nofallback"\n        },\n        {\n            "role": "linguist/s2p",\n            "ref": ":inference/s2p-deu"\n        }\n    ]\n}\n',
        'linguists/eng/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Chain English",\n    "language": "eng",\n    "scheme": "arpabet",\n    "exports": { "phonemes": [] },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g2p" },\n        { "role": "linguist/s2p", "ref": ":inference/s2p" }\n    ]\n}\n',
    },
    'lang-cmn': {
        'assets/already-pinyin.txt': 'zhong\tzh ong\nguo\tg uo\n',
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-cmn",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn", "path": "./linguists/cmn/linguist.json" } ],\n        "inference": [\n            { "id": "g2p", "path": "./inferences/g2p/inference.json" },\n            { "id": "s2p", "path": "./inferences/s2p/inference.json" }\n        ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-pinyin-engine", "version": "1.0.0.0" }\n    ]\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Mandarin G2P",\n    "exports": {\n        "languages": [ { "language": "cmn", "scheme": "pinyin" } ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "dict",  "value": ["../../assets/already-pinyin.txt"], "mode": "copy" },\n                        { "type": "regex", "value": ["([\\\\p{Han}])+"], "mode": "convert" }\n                    ]\n                }\n            },\n            { "step": "model", "params": { "role": "backend" } },\n            { "step": "fallback", "params": { "useOriginal": true } }\n        ]\n    },\n    "imports": [\n        { "role": "backend", "ref": "wolf/test-pinyin-engine:inference/pinyin" }\n    ]\n}\n',
        'inferences/s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "Mandarin S2P",\n    "exports": {\n        "languages": [ { "language": "cmn", "scheme": "pinyin" } ]\n    },\n    "configuration": {}\n}\n',
        'linguists/cmn/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Mandarin",\n    "language": "cmn",\n    "scheme": "pinyin",\n    "exports": { "phonemes": [] },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g2p" },\n        { "role": "linguist/s2p", "ref": ":inference/s2p" }\n    ]\n}\n',
    },
    'lang-miscount': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-miscount",\n    "version": "1.0.0.0",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "A language whose G2P returns fewer words than it was given. Nothing shipped can do that; the stub does it on request so the guards against it have something to fire on.",\n    "contributions": {\n        "linguist": [ { "id": "nld-ds", "path": "./linguists/x/linguist.json" } ],\n        "inference": [\n            { "id": "g2p", "path": "./inferences/g2p/inference.json" },\n            { "id": "s2p", "path": "./inferences/s2p/inference.json" }\n        ]\n    }\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "stub-miscount",\n    "name": "Drops one word from every batch",\n    "exports": { "languages": [ { "language": "nld", "scheme": "ds" } ] },\n    "configuration": { "dropWords": 1 }\n}\n',
        'inferences/s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "Passthrough S2P",\n    "exports": { "languages": [ { "language": "nld", "scheme": "ds" } ] },\n    "configuration": {}\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Miscounting G2P",\n    "language": "nld",\n    "scheme": "ds",\n    "exports": { "phonemes": [], "openSet": true },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g2p" },\n        { "role": "linguist/s2p", "ref": ":inference/s2p" }\n    ]\n}\n',
    },
    'lang-model': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-model",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [\n            {\n                "id": "eng",\n                "path": "./linguists/eng/linguist.json"\n            },\n            {\n                "id": "deu",\n                "path": "./linguists/deu/linguist.json"\n            }\n        ],\n        "inference": [\n            {\n                "id": "chain",\n                "path": "./inferences/chain/inference.json"\n            },\n            {\n                "id": "strict",\n                "path": "./inferences/strict/inference.json"\n            },\n            {\n                "id": "s2p-eng",\n                "path": "./inferences/s2p-eng/inference.json"\n            },\n            {\n                "id": "s2p-deu",\n                "path": "./inferences/s2p-deu/inference.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/g2p-multi",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'inferences/chain/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "English G2P over the shared model",\n    "exports": {\n        "languages": [ { "language": "eng", "scheme": "arpabet" } ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "regex", "value": ["([A-Za-z\']+)"], "mode": "convert" }\n                    ]\n                }\n            },\n            { "step": "model", "params": { "role": "backend" } },\n            { "step": "fallback", "params": { "useOriginal": true } }\n        ]\n    },\n    "imports": [\n        { "role": "backend", "ref": "wolf/g2p-multi:inference/multig2p" }\n    ]\n}\n',
        'inferences/s2p-deu/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "deu S2P",\n    "exports": {\n        "languages": [\n            {\n                "language": "deu",\n                "scheme": "ds"\n            }\n        ]\n    },\n    "configuration": {}\n}\n',
        'inferences/s2p-eng/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "eng S2P",\n    "exports": {\n        "languages": [\n            {\n                "language": "eng",\n                "scheme": "arpabet"\n            }\n        ]\n    },\n    "configuration": {}\n}\n',
        'inferences/strict/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "German G2P over the shared model",\n    "exports": {\n        "languages": [\n            {\n                "language": "deu",\n                "scheme": "ds"\n            }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        {\n                            "type": "regex",\n                            "value": [\n                                "([A-Za-z\']+)"\n                            ],\n                            "mode": "convert"\n                        }\n                    ]\n                }\n            },\n            {\n                "step": "model",\n                "params": {\n                    "role": "backend"\n                }\n            }\n        ]\n    },\n    "imports": [\n        {\n            "role": "backend",\n            "ref": "wolf/g2p-multi:inference/multig2p"\n        }\n    ]\n}\n',
        'linguists/deu/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "deu",\n    "language": "deu",\n    "scheme": "ds",\n    "exports": {\n        "phonemes": []\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/strict"\n        },\n        {\n            "role": "linguist/s2p",\n            "ref": ":inference/s2p-deu"\n        }\n    ]\n}\n',
        'linguists/eng/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "eng",\n    "language": "eng",\n    "scheme": "arpabet",\n    "exports": {\n        "phonemes": []\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/chain"\n        },\n        {\n            "role": "linguist/s2p",\n            "ref": ":inference/s2p-eng"\n        }\n    ]\n}\n',
    },
    'lang-runaway': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-runaway",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [\n            {\n                "id": "nld",\n                "path": "./linguists/nld/linguist.json"\n            }\n        ],\n        "inference": [\n            {\n                "id": "g2p",\n                "path": "./inferences/g2p/inference.json"\n            },\n            {\n                "id": "s2p",\n                "path": "./inferences/s2p/inference.json"\n            }\n        ]\n    }\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Passthrough G2P",\n    "exports": {\n        "languages": [\n            {\n                "language": "nld",\n                "scheme": "test"\n            }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "fallback",\n                "params": {\n                    "useOriginal": true\n                }\n            }\n        ]\n    }\n}\n',
        'inferences/s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "lua",\n    "name": "Runaway S2P",\n    "exports": {\n        "languages": [\n            {\n                "language": "nld",\n                "scheme": "test"\n            }\n        ]\n    },\n    "configuration": {\n        "file": "script.lua"\n    }\n}\n',
        'inferences/s2p/script.lua': 'function s2p(pronunciation)\n    if pronunciation == "loop" then\n        while true do end\n    end\n    return { pronunciation }\nend\n',
        'linguists/nld/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Runaway",\n    "language": "nld",\n    "scheme": "test",\n    "exports": {\n        "phonemes": [],\n        "openSet": true\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/g2p"\n        },\n        {\n            "role": "linguist/s2p",\n            "ref": ":inference/s2p"\n        }\n    ]\n}\n',
    },
    'lang-shallow': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-shallow",\n    "version": "1.0.0.0",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "A language whose composition stops at the pronunciation layer: it declares no linguist/s2p role, which is the shape a language package has when a voicebank supplies the phoneme stage.",\n    "contributions": {\n        "linguist": [ { "id": "nld-ds", "path": "./linguists/x/linguist.json" } ],\n        "inference": [ { "id": "g2p", "path": "./inferences/g2p/inference.json" } ]\n    }\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Fixed output G2P",\n    "exports": {\n        "languages": [ { "language": "nld", "scheme": "ds" } ],\n        "symbols": [ "a", "b" ],\n        "openSet": false\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            { "step": "fallback", "params": { "useOriginal": false, "defaultPronunciation": "a b" } }\n        ]\n    }\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Pronunciation only",\n    "language": "nld",\n    "scheme": "ds",\n    "exports": {\n        "phonemes": [ "a", "b", "c", "d" ],\n        "openSet": false\n    },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g2p" }\n    ]\n}\n',
    },
    'lang-yue': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-lang-yue",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "yue", "path": "./linguists/yue/linguist.json" } ],\n        "inference": [\n            { "id": "g2p", "path": "./inferences/g2p/inference.json" },\n            { "id": "s2p", "path": "./inferences/s2p/inference.json" }\n        ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-pinyin-engine", "version": "1.0.0.0" }\n    ]\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Cantonese G2P",\n    "exports": {\n        "languages": [ { "language": "yue", "scheme": "jyutping" } ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            {\n                "step": "verify",\n                "params": {\n                    "entries": [\n                        { "type": "regex", "value": ["([\\\\p{Han}])+"], "mode": "convert" }\n                    ]\n                }\n            },\n            { "step": "model", "params": { "role": "backend" } },\n            { "step": "fallback", "params": { "useOriginal": true } }\n        ]\n    },\n    "imports": [\n        { "role": "backend", "ref": "wolf/test-pinyin-engine:inference/pinyin" }\n    ]\n}\n',
        'inferences/s2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "name": "Cantonese S2P",\n    "exports": {\n        "languages": [ { "language": "yue", "scheme": "jyutping" } ]\n    },\n    "configuration": {}\n}\n',
        'linguists/yue/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Cantonese",\n    "language": "yue",\n    "scheme": "jyutping",\n    "exports": { "phonemes": [] },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g2p" },\n        { "role": "linguist/s2p", "ref": ":inference/s2p" }\n    ]\n}\n',
    },
    'multi-scheme': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-multi-scheme",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [\n            { "id": "cmn-pinyin", "path": "./linguists/a/linguist.json" },\n            { "id": "cmn-bopomofo", "path": "./linguists/b/linguist.json" }\n        ]\n    }\n}\n',
        'linguists/a/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn", "scheme": "pinyin" }\n',
        'linguists/b/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn", "scheme": "bopomofo" }\n',
    },
    'no-language': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-no-language",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ]\n    }\n}\n',
        'linguists/x/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "scheme": "pinyin" }\n',
    },
    'no-scheme': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-no-scheme",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ]\n    }\n}\n',
        'linguists/x/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn" }\n',
    },
    'options-nonempty': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-options-nonempty",\n    "version": "1.0.0.0",\n    "compatVersion": "1.0.0.0",\n    "runtimeLevel": 1,\n    "description": "A language whose composition stops at the pronunciation layer: it declares no linguist/s2p role, which is the shape a language package has when a voicebank supplies the phoneme stage.",\n    "contributions": {\n        "linguist": [\n            {\n                "id": "nld-ds",\n                "path": "./linguists/x/linguist.json"\n            }\n        ],\n        "inference": [\n            {\n                "id": "g2p",\n                "path": "./inferences/g2p/inference.json"\n            }\n        ]\n    }\n}\n',
        'inferences/g2p/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Fixed output G2P",\n    "exports": {\n        "languages": [ { "language": "nld", "scheme": "ds" } ],\n        "symbols": [ "a", "b" ],\n        "openSet": false\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [\n            { "step": "fallback", "params": { "useOriginal": false, "defaultPronunciation": "a b" } }\n        ]\n    }\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist",\n    "level": 1,\n    "variant": "wolf",\n    "name": "Pronunciation only",\n    "language": "nld",\n    "scheme": "ds",\n    "exports": {\n        "phonemes": [\n            "a",\n            "b",\n            "c",\n            "d"\n        ],\n        "openSet": false\n    },\n    "configuration": {},\n    "imports": [\n        {\n            "role": "linguist/g2p",\n            "ref": ":inference/g2p",\n            "options": {\n                "depth": 2\n            }\n        }\n    ]\n}\n',
    },
    'pair-mismatch': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-pair-mismatch",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ],\n        "inference": [\n            { "id": "g", "path": "./inferences/g/inference.json" },\n            { "id": "s", "path": "./inferences/s/inference.json" }\n        ]\n    }\n}\n',
        'inferences/g/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P", "level": 1, "variant": "pipe-chain",\n    "exports": { "languages": [ { "language": "yue", "scheme": "jyutping" } ] },\n    "configuration": { "formatVersion": 1, "steps": [ { "step": "fallback" } ] }\n}\n',
        'inferences/s/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P", "level": 1, "variant": "direct",\n    "exports": { "languages": [ { "language": "cmn", "scheme": "pinyin" } ] },\n    "configuration": {}\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf",\n    "language": "cmn", "scheme": "pinyin",\n    "exports": { "phonemes": [] },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g" },\n        { "role": "linguist/s2p", "ref": ":inference/s" }\n    ]\n}\n',
    },
    'pair-omitted': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-pair-omitted",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ],\n        "inference": [\n            { "id": "g", "path": "./inferences/g/inference.json" },\n            { "id": "s", "path": "./inferences/s/inference.json" }\n        ]\n    }\n}\n',
        'inferences/g/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P", "level": 1, "variant": "pipe-chain",\n    "exports": {},\n    "configuration": { "formatVersion": 1, "steps": [ { "step": "fallback" } ] }\n}\n',
        'inferences/s/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P", "level": 1, "variant": "direct",\n    "exports": { "languages": [ { "language": "cmn", "scheme": "pinyin" } ] },\n    "configuration": {}\n}\n',
        'linguists/x/linguist.json': '{\n    "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf",\n    "language": "cmn", "scheme": "pinyin",\n    "exports": { "phonemes": [] },\n    "configuration": {},\n    "imports": [\n        { "role": "linguist/g2p", "ref": ":inference/g" },\n        { "role": "linguist/s2p", "ref": ":inference/s" }\n    ]\n}\n',
    },
    'pinyin-engine': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-pinyin-engine",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "inference": [ { "id": "pinyin", "path": "./inferences/pinyin/inference.json" } ]\n    }\n}\n',
        'inferences/pinyin/dict/cantonese/phrases_dict.txt': '',
        'inferences/pinyin/dict/cantonese/phrases_map.txt': '',
        'inferences/pinyin/dict/cantonese/trans_word.txt': '',
        'inferences/pinyin/dict/cantonese/user_dict.txt': '',
        'inferences/pinyin/dict/cantonese/word.txt': '中:zung1\n国:gwok3\n',
        'inferences/pinyin/dict/mandarin/phrases_dict.txt': '银行:yín,háng\n',
        'inferences/pinyin/dict/mandarin/phrases_map.txt': '行:23\n',
        'inferences/pinyin/dict/mandarin/trans_word.txt': '銀:银\n',
        'inferences/pinyin/dict/mandarin/user_dict.txt': '',
        'inferences/pinyin/dict/mandarin/word.txt': '中:zhōng\n国:guó\n银:yín\n行:xíng,háng\n',
        'inferences/pinyin/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "algo-pinyin",\n    "name": "Test cpp-pinyin engine",\n    "exports": {\n        "languages": [\n            { "language": "cmn", "scheme": "pinyin" },\n            { "language": "yue", "scheme": "jyutping" }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "dictRoot": "./dict",\n        "languageMap": [\n            { "language": "cmn", "scheme": "pinyin", "ref": "mandarin" },\n            { "language": "yue", "scheme": "jyutping", "ref": "cantonese" }\n        ]\n    }\n}\n',
    },
    'pinyin-engine-rival': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-pinyin-engine-rival",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "inference": [ { "id": "pinyin", "path": "./inferences/pinyin/inference.json" } ]\n    }\n}\n',
        'inferences/pinyin/dict/cantonese/phrases_dict.txt': '',
        'inferences/pinyin/dict/cantonese/phrases_map.txt': '',
        'inferences/pinyin/dict/cantonese/trans_word.txt': '',
        'inferences/pinyin/dict/cantonese/user_dict.txt': '',
        'inferences/pinyin/dict/cantonese/word.txt': '中:zung1\n国:gwok3\n',
        'inferences/pinyin/dict/mandarin/phrases_dict.txt': '银行:yín,háng\n',
        'inferences/pinyin/dict/mandarin/phrases_map.txt': '行:23\n',
        'inferences/pinyin/dict/mandarin/trans_word.txt': '銀:银\n',
        'inferences/pinyin/dict/mandarin/user_dict.txt': '',
        'inferences/pinyin/dict/mandarin/word.txt': '中:zhōng\n国:guó\n银:yín\n行:xíng,háng\n',
        'inferences/pinyin/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "algo-pinyin",\n    "name": "Rival cpp-pinyin engine",\n    "exports": {\n        "languages": [\n            { "language": "cmn", "scheme": "pinyin" },\n            { "language": "yue", "scheme": "jyutping" }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "dictRoot": "./dict",\n        "languageMap": [\n            { "language": "cmn", "scheme": "pinyin", "ref": "mandarin" },\n            { "language": "yue", "scheme": "jyutping", "ref": "cantonese" }\n        ]\n    }\n}\n',
    },
    'pinyin-rollback': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-pinyin-rollback",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "inference": [\n            { "id": "pinyin", "path": "./inferences/pinyin/inference.json" },\n            { "id": "broken", "path": "./inferences/broken/inference.json" }\n        ]\n    }\n}\n',
        'inferences/broken/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "pipe-chain",\n    "name": "Fails after the pinyin module has claimed the dictionary root",\n    "configuration": {\n        "formatVersion": 1,\n        "steps": [ { "step": "fallback" } ],\n        "thisKeyDoesNotExist": 1\n    }\n}\n',
        'inferences/pinyin/dict/cantonese/phrases_dict.txt': '',
        'inferences/pinyin/dict/cantonese/phrases_map.txt': '',
        'inferences/pinyin/dict/cantonese/trans_word.txt': '',
        'inferences/pinyin/dict/cantonese/user_dict.txt': '',
        'inferences/pinyin/dict/cantonese/word.txt': '中:zung1\n国:gwok3\n',
        'inferences/pinyin/dict/mandarin/phrases_dict.txt': '银行:yín,háng\n',
        'inferences/pinyin/dict/mandarin/phrases_map.txt': '行:23\n',
        'inferences/pinyin/dict/mandarin/trans_word.txt': '銀:银\n',
        'inferences/pinyin/dict/mandarin/user_dict.txt': '',
        'inferences/pinyin/dict/mandarin/word.txt': '中:zhōng\n国:guó\n银:yín\n行:xíng,háng\n',
        'inferences/pinyin/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.G2P",\n    "level": 1,\n    "variant": "algo-pinyin",\n    "name": "Test cpp-pinyin engine",\n    "exports": {\n        "languages": [\n            { "language": "cmn", "scheme": "pinyin" },\n            { "language": "yue", "scheme": "jyutping" }\n        ]\n    },\n    "configuration": {\n        "formatVersion": 1,\n        "dictRoot": "./dict",\n        "languageMap": [\n            { "language": "cmn", "scheme": "pinyin", "ref": "mandarin" },\n            { "language": "yue", "scheme": "jyutping", "ref": "cantonese" }\n        ]\n    }\n}\n',
    },
    'singer-bad-default': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-bad-default",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "languages": {\n        "cmn": "lang/a"\n    },\n    "defaultLanguage": "jpn",\n    "imports": [\n        {\n            "role": "lang/a",\n            "ref": ":linguist/cmn-pinyin"\n        },\n        {\n            "role": "lang/b",\n            "ref": ":linguist/jpn-romaji"\n        }\n    ]\n}\n',
    },
    'singer-bad-role': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-bad-role",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "languages": {\n        "cmn": "lang/missing"\n    },\n    "defaultLanguage": "cmn",\n    "imports": [\n        {\n            "role": "lang/a",\n            "ref": ":linguist/cmn-pinyin"\n        },\n        {\n            "role": "lang/b",\n            "ref": ":linguist/jpn-romaji"\n        }\n    ]\n}\n',
    },
    'singer-bad-shape': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-bad-shape",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "languages": [\n        "cmn"\n    ],\n    "imports": [\n        {\n            "role": "lang/a",\n            "ref": ":linguist/cmn-pinyin"\n        },\n        {\n            "role": "lang/b",\n            "ref": ":linguist/jpn-romaji"\n        }\n    ]\n}\n',
    },
    'singer-chain': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-chain",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-lang-chain", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Chain Singer",\n    "languages": {\n        "eng": "lang/eng",\n        "deu": "lang/deu"\n    },\n    "defaultLanguage": "eng",\n    "imports": [\n        {\n            "role": "lang/eng",\n            "ref": "wolf/test-lang-chain:linguist/eng"\n        },\n        {\n            "role": "lang/deu",\n            "ref": "wolf/test-lang-chain:linguist/deu"\n        }\n    ]\n}\n',
    },
    'singer-inference-route': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-inference-route",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ],\n        "inference": [ { "id": "s", "path": "./inferences/s/inference.json" } ]\n    }\n}\n',
        'inferences/s/inference.json': '{\n    "interface": "org.openvpi.wolf.inference.S2P",\n    "level": 1,\n    "variant": "direct",\n    "configuration": {}\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "zxx": "lang/model"\n    },\n    "defaultLanguage": "zxx",\n    "imports": [\n        {\n            "role": "lang/model",\n            "ref": ":inference/s"\n        }\n    ]\n}\n',
    },
    'singer-lang-mismatch': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-lang-mismatch",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [\n            {\n                "id": "s",\n                "path": "./singers/s/singer.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/lang-zxx",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "cmn": "lang/passthrough"\n    },\n    "defaultLanguage": "cmn",\n    "imports": [\n        {\n            "role": "lang/passthrough",\n            "ref": "wolf/lang-zxx:linguist/zxx-passthrough"\n        }\n    ]\n}\n',
    },
    'singer-markers': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-markers",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [\n            {\n                "id": "s",\n                "path": "./singers/s/singer.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/lang-zxx",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer With Markers",\n    "languages": {\n        "zxx": "lang/passthrough"\n    },\n    "defaultLanguage": "zxx",\n    "reservedPhonemes": [\n        "EP"\n    ],\n    "imports": [\n        {\n            "role": "lang/passthrough",\n            "ref": "wolf/lang-zxx:linguist/zxx-passthrough"\n        }\n    ]\n}\n',
    },
    'singer-miscount': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-miscount",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-lang-miscount", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "nld": "lang/nld"\n    },\n    "defaultLanguage": "nld",\n    "imports": [\n        {\n            "role": "lang/nld",\n            "ref": "wolf/test-lang-miscount:linguist/nld-ds"\n        }\n    ]\n}\n',
    },
    'singer-model': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-model",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [\n            {\n                "id": "s",\n                "path": "./singers/s/singer.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/test-lang-model",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Model Singer",\n    "languages": {\n        "eng": "lang/eng",\n        "deu": "lang/deu"\n    },\n    "defaultLanguage": "eng",\n    "imports": [\n        {\n            "role": "lang/eng",\n            "ref": "wolf/test-lang-model:linguist/eng"\n        },\n        {\n            "role": "lang/deu",\n            "ref": "wolf/test-lang-model:linguist/deu"\n        }\n    ]\n}\n',
    },
    'singer-no-default': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-no-default",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "languages": {\n        "cmn": "lang/a"\n    },\n    "imports": [\n        {\n            "role": "lang/a",\n            "ref": ":linguist/cmn-pinyin"\n        },\n        {\n            "role": "lang/b",\n            "ref": ":linguist/jpn-romaji"\n        }\n    ]\n}\n',
    },
    'singer-none': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-none",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "configuration": {},\n    "imports": [\n        { "role": "lang/a", "ref": ":linguist/cmn-pinyin" },\n        { "role": "lang/b", "ref": ":linguist/jpn-romaji" }\n    ]\n}\n',
    },
    'singer-ok': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-ok",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    }\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "languages": {\n        "cmn": "lang/a",\n        "jpn": "lang/b"\n    },\n    "defaultLanguage": "cmn",\n    "imports": [\n        {\n            "role": "lang/a",\n            "ref": ":linguist/cmn-pinyin"\n        },\n        {\n            "role": "lang/b",\n            "ref": ":linguist/jpn-romaji"\n        }\n    ]\n}\n',
    },
    'singer-runaway': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-runaway",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [\n            {\n                "id": "s",\n                "path": "./singers/s/singer.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/test-lang-runaway",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Runaway Singer",\n    "languages": {\n        "nld": "lang/nld"\n    },\n    "defaultLanguage": "nld",\n    "imports": [\n        {\n            "role": "lang/nld",\n            "ref": "wolf/test-lang-runaway:linguist/nld"\n        }\n    ]\n}\n',
    },
    'singer-shallow': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-shallow",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-lang-shallow", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "nld": "lang/nld"\n    },\n    "defaultLanguage": "nld",\n    "imports": [\n        {\n            "role": "lang/nld",\n            "ref": "wolf/test-lang-shallow:linguist/nld-ds"\n        }\n    ]\n}\n',
    },
    'singer-wrong-target': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-wrong-target",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [\n            {\n                "id": "s",\n                "path": "./singers/s/singer.json"\n            }\n        ]\n    },\n    "dependencies": [\n        {\n            "id": "wolf/lang-zxx",\n            "version": "1.0.0.0"\n        }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "zxx": "lang/model"\n    },\n    "defaultLanguage": "zxx",\n    "imports": [\n        {\n            "role": "lang/model",\n            "ref": "wolf/lang-zxx:inference/zxx-g2p"\n        }\n    ]\n}\n',
    },
    'singer-zh': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-zh",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/test-lang-cmn", "version": "1.0.0.0" },\n        { "id": "wolf/test-lang-yue", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Chinese Singer",\n    "languages": {\n        "cmn": "lang/cmn",\n        "yue": "lang/yue"\n    },\n    "defaultLanguage": "cmn",\n    "imports": [\n        {\n            "role": "lang/cmn",\n            "ref": "wolf/test-lang-cmn:linguist/cmn"\n        },\n        {\n            "role": "lang/yue",\n            "ref": "wolf/test-lang-yue:linguist/yue"\n        }\n    ]\n}\n',
    },
    'singer-zxx': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-zxx",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/lang-zxx", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "zxx": "lang/passthrough"\n    },\n    "defaultLanguage": "zxx",\n    "imports": [\n        {\n            "role": "lang/passthrough",\n            "ref": "wolf/lang-zxx:linguist/zxx-passthrough"\n        }\n    ]\n}\n',
    },
    'singer-zxx-v2': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-singer-zxx",\n    "version": "1.0.1.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "singer": [ { "id": "s", "path": "./singers/s/singer.json" } ]\n    },\n    "dependencies": [\n        { "id": "wolf/lang-zxx", "version": "1.0.0.0" }\n    ]\n}\n',
        'singers/s/singer.json': '{\n    "interface": "org.openvpi.wolf.test.Singer",\n    "level": 1,\n    "variant": "stub",\n    "name": "Stub Singer",\n    "languages": {\n        "zxx": "lang/passthrough"\n    },\n    "defaultLanguage": "zxx",\n    "imports": [\n        {\n            "role": "lang/passthrough",\n            "ref": "wolf/lang-zxx:linguist/zxx-passthrough"\n        }\n    ]\n}\n',
    },
    'unknown-field': {
        'desc.json': '{\n    "$version": "1.0",\n    "id": "wolf/test-unknown-field",\n    "version": "1.0.0.0",\n    "runtimeLevel": 1,\n    "contributions": {\n        "linguist": [ { "id": "cmn-pinyin", "path": "./linguists/x/linguist.json" } ]\n    }\n}\n',
        'linguists/x/linguist.json': '{ "interface": "org.openvpi.wolf.linguist.WolfLinguist", "level": 1, "variant": "wolf", "exports": { "phonemes": [] }, "configuration": {}, "imports": [ { "role": "linguist/g2p", "ref": ":inference/g" }, { "role": "linguist/s2p", "ref": ":inference/s" } ], "language": "cmn", "scheme": "pinyin", "nonsense": 1 }\n',
    },
}


def write_tree(root: Path) -> None:
    """Write every fixture file below root."""
    for package in sorted(PACKAGES):
        for relative, text in sorted(PACKAGES[package].items()):
            path = root / package / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode("utf-8"))


def compare(root: Path) -> list[str]:
    """Return a line per difference between the table and the tree below root."""
    differences: list[str] = []
    expected: set[str] = set()
    for package in sorted(PACKAGES):
        for relative, text in sorted(PACKAGES[package].items()):
            expected.add(f"{package}/{relative}")
            path = root / package / relative
            if not path.is_file():
                differences.append(f"missing: {package}/{relative}")
                continue
            if path.read_bytes() != text.encode("utf-8"):
                differences.append(f"differs: {package}/{relative}")
    if root.is_dir():
        for path in sorted(root.rglob("*")):
            if path.is_file():
                relative = path.relative_to(root).as_posix()
                if relative not in expected:
                    differences.append(f"unexpected: {relative}")
    return differences


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the wolf test fixture packages.")
    parser.add_argument("--output", type=Path, help="directory to write the fixture packages into")
    parser.add_argument("--check", type=Path, metavar="DIR",
                        help="compare an existing tree against the table and fail on any difference")
    parser.add_argument("--list", action="store_true", help="print the package names")
    args = parser.parse_args()

    if args.list:
        for package in sorted(PACKAGES):
            print(package)
        return 0

    if args.check is not None:
        differences = compare(args.check)
        for line in differences[:50]:
            print(line, file=sys.stderr)
        if differences:
            print(f"{len(differences)} differences against {args.check}", file=sys.stderr)
            return 1
        print(f"{len(PACKAGES)} packages match {args.check}")
        return 0

    if args.output is None:
        parser.error("one of --output, --check or --list is required")
    write_tree(args.output)
    files = sum(len(files) for files in PACKAGES.values())
    print(f"{len(PACKAGES)} packages, {files} files written to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
